import { createHmac } from "crypto";

// ─────────────────────────────────────────────────────────────────────────
// Signs outbound links so they route through /api/redirect. The signature
// (not secrecy) exists to prove the link was generated by us — it stops
// someone from constructing an arbitrary /api/redirect?u=... open-redirect
// URL that isn't actually from a scanned inbound email.
// ─────────────────────────────────────────────────────────────────────────

function getKey(): string {
  return process.env.SESSION_SECRET ?? "dev-only-insecure-key";
}

function sign(url: string, flagged: boolean): string {
  return createHmac("sha256", getKey())
    .update(`${flagged ? "1" : "0"}:${url}`)
    .digest("hex")
    .slice(0, 32);
}

export function signRedirectUrl(url: string, flagged: boolean): string {
  const token = sign(url, flagged);
  const params = new URLSearchParams({ u: url, t: token, f: flagged ? "1" : "0" });
  return `/api/redirect?${params.toString()}`;
}

export function verifyRedirectToken(url: string, flagged: boolean, token: string): boolean {
  return sign(url, flagged) === token;
}
