/**
 * Office import/export regression tests.
 *
 *   npm run test:office-io
 *
 * Exercises the real code paths end-to-end rather than asserting on strings:
 *  - src/lib/docx-export.ts builds a .docx, which is then re-read with mammoth
 *    (an independent, Word-compatible OOXML parser). If Word could not open the
 *    file, mammoth would not parse it either.
 *  - src/lib/pptx-import.ts parses a .pptx generated by pptxgenjs, checking
 *    text, speaker notes, tables, positions and run formatting survive.
 *
 * Both modules are browser code (DOMParser, Node, atob), so jsdom supplies the
 * globals. There is no "type": "module" in package.json, so everything lives
 * inside main() — top-level await isn't available in the CJS output.
 */

import { JSDOM } from "jsdom";

async function main() {
  const dom = new JSDOM("<!doctype html><html><body></body></html>");
  // The modules under test are browser code; give them the globals they expect.
  (globalThis as unknown as { DOMParser: unknown }).DOMParser = dom.window.DOMParser;
  (globalThis as unknown as { Node: unknown }).Node = dom.window.Node;
  (globalThis as unknown as { atob: unknown }).atob = (b64: string) =>
    Buffer.from(b64, "base64").toString("binary");
  (globalThis as unknown as { window: unknown }).window = dom.window;

  let pass = 0, fail = 0;
  const check = (label: string, cond: boolean, extra = "") => {
    if (cond) { pass++; console.log("  ✓", label); }
    else { fail++; console.log("  ✗", label, extra); }
  };

  // ── DOCX round-trip: our writer → mammoth's reader ────────────────────────
  console.log("\nDOCX round-trip");
  const { htmlToDocxBlob } = await import("../src/lib/docx-export");
  const srcHtml = `<h1>Title</h1><p>Hello <strong>bold</strong> world.</p>
<ul><li>Alpha</li><li>Beta</li></ul>
<table><tr><th>Name</th><th>Qty</th></tr><tr><td>Widget</td><td>7</td></tr></table>`;
  const blob = await htmlToDocxBlob(srcHtml, "RT");
  const buf = Buffer.from(await blob.arrayBuffer());

  const mammoth = await import("mammoth");
  const back = await (mammoth as unknown as {
    convertToHtml: (o: { buffer: Buffer }) => Promise<{ value: string }>;
  }).convertToHtml({ buffer: buf });
  const text = back.value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");

  check("title survives", text.includes("RT"), text.slice(0, 120));
  check("body text survives", text.includes("Hello bold world"), text.slice(0, 120));
  check("list items survive", text.includes("Alpha") && text.includes("Beta"));
  check("table cells survive", text.includes("Widget") && text.includes("7"));
  check("bold preserved as <strong>", /<strong>bold<\/strong>/.test(back.value), back.value.slice(0, 200));
  check("heading preserved", /<h1[^>]*>/.test(back.value), back.value.slice(0, 120));

  // Two <w:pPr> in one <w:p> is invalid OOXML — Word rejects or "repairs" it.
  const JSZip = (await import("jszip")).default;
  const zip = await JSZip.loadAsync(buf);
  const docXml = await zip.file("word/document.xml")!.async("string");
  const dupes = [...docXml.matchAll(/<w:p>(?:(?!<\/w:p>)[\s\S])*?<w:pPr>(?:(?!<\/w:p>)[\s\S])*?<w:pPr>/g)];
  check("no duplicate <w:pPr> in a paragraph", dupes.length === 0, `found ${dupes.length}`);

  for (const name of Object.keys(zip.files)) {
    if (!name.endsWith(".xml") && !name.endsWith(".rels")) continue;
    const xml = await zip.file(name)!.async("string");
    const parsed = new dom.window.DOMParser().parseFromString(xml, "application/xml");
    check(`${name} is well-formed`, parsed.getElementsByTagName("parsererror").length === 0);
  }

  // ── PPTX: generate with pptxgenjs, parse with our importer ────────────────
  console.log("\nPPTX import");
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  const s1 = pptx.addSlide();
  s1.addText("Quarterly Review", { x: 0.5, y: 0.5, w: 8, h: 1, fontSize: 36, bold: true });
  s1.addText("Prepared by the team", { x: 0.5, y: 1.8, w: 8, h: 0.6, fontSize: 18 });
  s1.addNotes("Remember to mention the hiring plan.");
  const s2 = pptx.addSlide();
  s2.addText("Second slide", { x: 1, y: 1, w: 6, h: 0.8, fontSize: 28 });
  s2.addTable([[{ text: "Region" }, { text: "Revenue" }], [{ text: "EMEA" }, { text: "120" }]], { x: 1, y: 2, w: 6 });

  const pptxBuf = await pptx.write({ outputType: "nodebuffer" }) as Buffer;
  const file = {
    arrayBuffer: async () => pptxBuf.buffer.slice(pptxBuf.byteOffset, pptxBuf.byteOffset + pptxBuf.byteLength),
    name: "t.pptx",
  } as unknown as File;

  const { parsePptx, describeImport } = await import("../src/lib/pptx-import");
  const slides = await parsePptx(file);
  console.log("  parsed:", describeImport(slides));

  check("two slides parsed", slides.length === 2, `got ${slides.length}`);
  const allText = slides.flatMap(s => s.elements.map(e => e.content ?? "")).join(" | ");
  check("slide 1 title text", allText.includes("Quarterly Review"), allText.slice(0, 160));
  check("slide 1 subtitle", allText.includes("Prepared by the team"));
  check("slide 2 text", allText.includes("Second slide"));
  check("speaker notes imported", slides[0].notes.includes("hiring plan"), JSON.stringify(slides[0].notes));
  const tbl = slides[1].elements.find(e => e.type === "table");
  check("table imported", !!tbl && JSON.stringify(tbl.tableRows).includes("EMEA"), JSON.stringify(tbl?.tableRows));
  check("positions within canvas", slides.every(s => s.elements.every(e =>
    e.x >= 0 && e.y >= 0 && e.x <= 960 && e.y <= 540 && e.w > 0 && e.h > 0)));
  check("bold detected on title", slides[0].elements.some(e => e.style?.bold === true));

  // ── Garbage input must fail loudly, not return junk ───────────────────────
  console.log("\nPPTX error handling");
  const junk = {
    arrayBuffer: async () => Buffer.from("not a zip at all").buffer,
    name: "x.pptx",
  } as unknown as File;
  let threw = false;
  try { await parsePptx(junk); } catch { threw = true; }
  check("garbage file throws instead of returning junk", threw);

  console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}

main().catch(err => { console.error(err); process.exit(1); });
